version: '2'
services:
  db:
    image: postgres
  web:
    image: netmask/cuandoesquincena
    command: mix phoenix.server
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - "db:db"