version: "2"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/app/volumes/proxy/certs:/etc/nginx/certs:rw"

  cuandoesquincena:
    image: netmask/cuandoesquincena
    container_name: quincenasite
    volumes:
      - "/app/volumes/conf.d:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=cuandoesquincena.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=cuandoesquincena.com
      - LETSENCRYPT_EMAIL=jonathan@quincenalabs.com
    links:
      - "db:db"
    networks:
      - proxy-tier
  db:
    image: postgres

networks:
  proxy-tier:
    external:
      name: nginx-proxy
